baseURL = 'https://maiboii.github.io'
languageCode = 'en-us'
title = 'MaiBoii'
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true


[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
endLevel = 3

[outputs]
home = ["HTML", "RSS", "JSON"]

ignoreFiles = ["_page.md", "README.md"]