[[main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30
