env = 'production'
title=  'MaiBoii'
description= "Just Keep Enjoying"
keywords= ['Blog', 'Portfolio', 'PaperMod']
author= 'MaiBoii'
DateFormat= "January 2, 2006"

defaultTheme= 'light'
disableThemeToggle= false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
mainsections = ["page", "post", "archive", "search"]

[homeInfoParams]
Title = "MaiBoii's TIL"
Content = "공부한거 정리하고 번역도 하는 곳"

[[socialIcons]]
name = "github"
title = "My Github"
url = "https://github.com/MaiBoii"


custom_css = ["css/main.css"]