title: MaiBoii
description: Just Keep Busy...
author: James Ma
avatar: /logo.png
email: 20183010@gs.cwnu.ac.kr

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: SeungWook Ma
  links:
    - https://github.com/MaiBoii
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
