baseURL = 'https://maiboii.github.io'
languageCode = 'en-us'
title = 'MaiBoii'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts =false
buildFuture = false
buildExpired = false

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40
